CBV/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from cbvapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.MyCBV.as_view(),name='index'),
    path('cbvapp/',include('cbvapp.urls',namespace='cbvapp')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cbvapp/urls.py
from django.urls import path
from cbvapp import views

app_name='cbvapp'

urlpatterns = [
    path('',views.collageList.as_view(),name='list'),
    path('<int:pk>/',views.collageDetail.as_view(),name='detail'),
]

cbvapp/models.py
from django.db import models

class Collage(models.Model):
    name = models.CharField(max_length=250)
    principal_name = models.CharField(max_length=250)
    location = models.CharField(max_length=200)
    contact_no = models.PositiveIntegerField()
    registered_at = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return self.name

class student(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField(max_length=250, unique=True)
    contact = models.PositiveIntegerField()
    age = models.PositiveIntegerField()
    collage = models.ForeignKey(Collage,on_delete=models.CASCADE,related_name='students')
    pic = models.FileField(upload_to='images/%Y/%m/%d')

    def __str__(self):
        return self.name

cbvapp/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView
from .models import Collage,student

class MyCBV(TemplateView):
    template_name= 'index.html'

class collageList(ListView):
    context_object_name = 'collages_list'
    model = Collage

class collageDetail(DetailView):
    context_object_name = 'detail'
    model= Collage
    template_name = 'cbvapp/collage_detail.html'

cbvapp/templates/cbvapp/collage_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container-fluid">
  <div class="row py-5 px-0" style='background:url("https://www.sanger.ac.uk/sites/default/files/campus4.jpg");background-attachment:fixed;'>
    <div class="col-md-4 text-white text-center mx-auto" style='background:rgba(0,0,0,0.5)'>
      <h3>{{ detail.name }}</h3>
      <p>{{detail.location}}</p>
      <h5>{{ detail.principal_name }}(Principal)</h5>
      <span><i class="fas fa-blender-phone text-white"></i>{{detail.contact_no}}</span>
    </div>
  </div>
  <div class="row bg-light">
    <div class="col-md-12">
      <h1 class='text-warning text-center'>Our Students</h1>
      <div class="card-deck">
        {% for student in detail.students.all %}
          <div class="card text-center">
            <div class="card-header">
              <img src="/media/{{student.pic}}" alt="No Picture" height=200 width=100% class='card-img-top'>
            </div>
            <div class="card-body">
              <div class="card-title">
                <h3>{{student.name}}</h3>
                <span>({{student.age}} yrs. old )</span>
              </div>
              <div class="card-text">
                <span class='my-2'><i class="fas fa-envelope-square"></i>{{student.email}}</span><br/>
                <span><i class="fas fa-phone-volume"></i>{{student.contact}}</span>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

cbvapp/templates/cbvapp/collage_list.html
{% extends "base.html" %}
{% block body_block %}
<div class="row">
    <div class="col-md-12">
      <h1 class='text-warning'>Here is the list of collages</h1>
      <ul class='list-group'><ol>
        {% for collage in collages_list %}
        <li>
          <li class='list-group-item'>
            <a href="{{collage.id}}">{{collage.id}} {{ collage.name }}</a> 
          </li>
        </li>
        {% endfor %}
      </ol>
      </ul>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <title>Mysite</title>
    <style media="screen">
      i{
        padding:5px;
        color:blue;
      }
    </style>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 px-0">
          <nav class='navbar navbar-expand-sm bg-dark navbar-dark'>
            <a href="{% url "cbvapp:list" %}" class='navbar-brand'>Collages</a>
            <ul class='navbar-nav mx-auto'>
              <li class='nav-item'>
                <a href="{% url "index"%}" class='nav-link'>Home</a>
              </li>
              <li class='nav-item'>
                <a href="{% url "admin:index" %}" class='nav-link'>Admin</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="row" style='height:400px;background:url("http://www.compassproperties.com/wp-content/uploads/2018/02/city-square2.jpg");background-size:100% 100%;'>
  <div class="col-md-12 px-0">
    <section>
      <div class="text-center text-white pt-5">
        <h1 class='display-1'><strong>It is awesome</strong> </h1>
        <p class=''>It is a paragraph</p>
      </div>
    </section>
  </div>
</div>
<div class="row">
  <div class="col-md-12 my-5 text-center text-warning">
    <h1>Who we are</h1>
  </div>
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <p>This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.</p>
      </div>
      <div class="col-md-4">
        <p>This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.</p>

      </div>
      <div class="col-md-4">
        <p>This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.This is a paragraph.</p>

      </div>
    </div>
  </div>
</div>
{% endblock %}